import { test, expect } from '../../frontend/e2e/fixtures'

// Every run targets a fresh dedicated database, never a user's account.
const username = 'e2e_' + Date.now()
const password = 'test-only-learning-2026'

test('registration, guide, quiz modal, persisted progress and simulated orders', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByRole('tab', { name: '注册', exact: true }).click()
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByPlaceholder('至少 10 位，建议使用较长的密码').fill(password)
  await page.getByLabel('确认密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '注册并开始学习' }).click()
  await expect(page.getByRole('heading', { name: '欢迎来到你的学习空间' })).toBeVisible()
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '下一步', exact: true }).click()
  await page.getByRole('button', { name: '开始第一课', exact: true }).click()
  await page.getByRole('tab', { name: '独立练习', exact: true }).click()
  await page.getByRole('radio', { name: /B.*17,000/ }).check()
  await page.getByRole('button', { name: '下一题', exact: true }).click()
  await page.getByRole('radio', { name: /C.*订单已提交/ }).check()
  await page.getByRole('button', { name: '提交答案' }).click()
  await expect(page.getByRole('heading', { name: '独立练习已完成 · 100%' })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('link', { name: '学习档案', exact: true }).click()
  await expect(page.getByText('20 XP', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '交易训练', exact: true }).click()
  await page.getByRole('spinbutton', { name: '委托价格', exact: true }).fill('22.00')
  await page.getByRole('button', { name: '提交模拟订单' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('待处理', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '下一教学日', exact: true }).click()
  await expect(page.getByText('已成交', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '账号菜单' }).click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByPlaceholder('至少 10 位，建议使用较长的密码').fill(password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('link', { name: '学习档案', exact: true }).click()
  await expect(page.getByText('20 XP', { exact: true })).toBeVisible()
})

test('desktop workspaces fit 1366x768 and mobile navigation remains reachable', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('tab', { name: '注册', exact: true }).click()
  await page.getByLabel('用户名', { exact: true }).fill('layout_' + Date.now())
  await page.getByPlaceholder('至少 10 位，建议使用较长的密码').fill(password)
  await page.getByLabel('确认密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '注册并开始学习' }).click()
  await page.getByRole('button', { name: '跳过引导', exact: true }).click()
  await page.setViewportSize({ width: 1366, height: 768 })
  for (const label of ['学习主页', '交易训练', '自由模拟', '策略实验', '学习档案', '数据状态']) {
    await page.getByRole('link', { name: label, exact: true }).click()
    await expect(page.locator('.main-content h1')).toBeVisible()
    expect(await page.locator('.main-content').evaluate(e => e.scrollHeight <= e.clientHeight + 2)).toBeTruthy()
    expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBeTruthy()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: '学习主页', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('link', { name: '学习档案', exact: true }).click()
  await expect(page.getByRole('heading', { name: '你的每一步，都有迹可循' })).toBeVisible()
})

test('a mistake becomes a new-case review and its schedule survives reload', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('tab', { name: '注册', exact: true }).click()
  await page.getByLabel('用户名', { exact: true }).fill('review_' + Date.now())
  await page.getByPlaceholder('至少 10 位，建议使用较长的密码').fill(password)
  await page.getByLabel('确认密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '注册并开始学习' }).click()
  await page.getByRole('button', { name: '跳过引导', exact: true }).click()
  await page.getByRole('button', { name: '继续学习', exact: true }).click()
  await page.getByRole('tab', { name: '独立练习', exact: true }).click()
  await page.getByRole('radio', { name: 'A 20,000 元', exact: true }).check()
  await page.getByRole('button', { name: '下一题', exact: true }).click()
  await page.getByRole('radio', { name: 'C 订单已提交，但还没有成交', exact: true }).check()
  await page.getByRole('button', { name: '提交答案', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('50%')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '学习提醒', exact: true }).click()
  await page.getByRole('button', { name: '开始复习', exact: true }).click()
  await expect(page.getByRole('group')).toContainText('36,000')
  await page.getByRole('radio', { name: 'C 30,000 元', exact: true }).check()
  await page.getByRole('button', { name: '提交复习答案', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('下次复习已安排')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: '学习提醒', exact: true }).click()
  await expect(page.getByText('连续答对 1 / 4 次')).toBeVisible()
  await expect(page.getByText('等待到期', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '开始复习' })).toHaveCount(0)
})
