import { test, expect } from '../../frontend/e2e/fixtures'

test('bilingual media playback, section seeking and saved listening positions', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('tab', { name: '注册', exact: true }).click()
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('audio_' + Date.now())
  await page.getByRole('textbox', { name: '密码 显示密码', exact: true }).fill('browser-audio-test-2026')
  await page.getByRole('textbox', { name: '确认密码', exact: true }).fill('browser-audio-test-2026')
  await page.getByRole('button', { name: '注册并开始学习', exact: true }).click()
  await page.getByRole('button', { name: '跳过引导', exact: true }).click()
  await page.getByRole('link', { name: '交易训练', exact: true }).click()
  await page.getByRole('tab', { name: '学习讲解', exact: true }).click()
  await page.getByRole('button', { name: '播放讲解', exact: true }).click()
  await expect.poll(() => page.locator('audio').evaluate(element => element.currentTime)).toBeGreaterThan(.2)
  await page.getByRole('button', { name: '暂停讲解', exact: true }).click()
  await page.getByRole('combobox', { name: '语速', exact: true }).selectOption('1.5')
  await page.getByRole('combobox', { name: '跳转讲解段落', exact: true }).selectOption({ label: '四个位置，各司其职' })
  await expect.poll(() => page.locator('audio').evaluate(element => element.currentTime)).toBeGreaterThan(20)
  await expect(page.getByText('收听位置已保存', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.locator('audio')).toHaveCount(0)
  await page.getByRole('tab', { name: '学习讲解', exact: true }).click()
  await expect.poll(() => page.locator('audio').evaluate(element => element.currentTime)).toBeGreaterThan(20)
  await expect(page.getByRole('combobox', { name: '语速', exact: true })).toHaveValue('1.5')
  await page.getByRole('combobox', { name: '朗读语言', exact: true }).selectOption('en')
  await expect(page.locator('audio')).toHaveAttribute('src', /\/en\//)
  await expect.poll(() => page.locator('audio').evaluate(element => element.duration)).toBeGreaterThan(80)
  await expect.poll(() => page.locator('audio').evaluate(element => element.currentTime)).toBe(0)
  await page.getByRole('button', { name: '播放讲解', exact: true }).click()
  await expect.poll(() => page.locator('audio').evaluate(element => element.currentTime)).toBeGreaterThan(.2)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('link', { name: '学习档案', exact: true }).click()
  await page.getByRole('button', { name: '我的听课记录', exact: true }).click()
  await expect(page.getByRole('link', { name: '继续收听', exact: true })).toHaveCount(2)
})
