import { test, expect } from '../../frontend/e2e/fixtures'

test('free practice keeps archived positions and reflections in a separate round', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('combobox').selectOption('en')
  await page.getByRole('tab', { name: 'Register', exact: true }).click()
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill('round_' + Date.now())
  await page.getByRole('textbox', { name: 'Password Show password', exact: true }).fill('Isolated-round-test-2026')
  await page.getByRole('textbox', { name: 'Confirm password', exact: true }).fill('Isolated-round-test-2026')
  await page.getByRole('button', { name: 'Register and start learning', exact: true }).click()
  await page.getByRole('button', { name: 'Skip tour', exact: true }).click()
  await page.getByRole('link', { name: 'Practice', exact: true }).click()
  await expect(page.getByText('Round 1 · Teaching day 20', { exact: true })).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Limit price', exact: true }).fill('22.00')
  await page.getByRole('button', { name: 'Place simulated order', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancel order', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'New round', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Archive and start again', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Return to practice', exact: true }).click()
  await page.getByRole('button', { name: 'Next teaching day', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Filled', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Reflect on this round', exact: true }).click()
  await page.getByRole('textbox', { name: 'Before-trade plan', exact: true }).fill('Use one lot to observe execution and fees.')
  await page.getByRole('textbox', { name: 'After-trade reflection', exact: true }).fill('The next teaching open was used to estimate the fill.')
  await page.getByRole('button', { name: 'Save plan and reflection', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Your plan and reflection were saved to your profile.')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'New round', exact: true }).click()
  await page.getByRole('button', { name: 'Archive and start again', exact: true }).click()
  await expect(page.getByText('Round 2 · Teaching day 20', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Round 2 · Teaching day 20', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Practice rounds', exact: true }).click()
  await page.getByRole('article').filter({ hasText: 'Round 1' }).getByRole('button', { name: 'View round', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Round 1 · Archived', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Positions', exact: true }).click()
  await expect(page.getByRole('tabpanel')).toContainText('100 shares')
  await expect(page.getByRole('button', { name: 'Cancel order', exact: true })).toHaveCount(0)
  await page.locator('.round-reflections summary').click()
  await expect(page.getByText('The next teaching open was used to estimate the fill.', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  const size = await page.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, dialog: document.querySelector('[role="dialog"]')!.getBoundingClientRect().toJSON() }))
  expect(size.documentWidth).toBe(size.width)
  expect(size.dialog.y).toBeGreaterThanOrEqual(0)
  expect(size.dialog.bottom).toBeLessThanOrEqual(844)
})
