""" initial local learning and simulation schema """
from alembic import op
import sqlalchemy as sa

revision = '0ac7d706b8a3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('mode', sa.String(length=191), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('frozen_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=191), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('lesson_id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('kind', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=191), nullable=False),
    sa.Column('source', sa.String(length=191), nullable=False),
    sa.Column('kind', sa.String(length=191), nullable=False),
    sa.Column('cash_delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=191), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source')
    )
    op.create_index(op.f('ix_ledger_account_id'), 'ledger', ['account_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('account_id', sa.String(length=191), nullable=False),
    sa.Column('symbol', sa.String(length=191), nullable=False),
    sa.Column('side', sa.String(length=191), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('filled_day', sa.Integer(), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('reduced_motion', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=191), nullable=False),
    sa.Column('symbol', sa.String(length=191), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sellable', sa.Integer(), nullable=False),
    sa.Column('frozen', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('lesson_id', sa.String(length=191), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('review_due', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflections',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('account_id', sa.String(length=191), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('fingerprint', sa.String(length=191), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('player_id', sa.String(length=191), nullable=False),
    sa.Column('lesson_id', sa.String(length=191), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    op.drop_table('requests')
    op.drop_table('reflections')
    op.drop_table('progress')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('players')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ledger_account_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_table('jobs')
    op.drop_table('attempts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

