import type { Narration } from '../features/audio/NarrationPlayer'
export type Bar = { day: number; open: string; close: string; high: string; low: string; volume: number; suspended: boolean }
export type Quote = { symbol: string; name: string; price: string; change: string; volume: number; suspended: boolean }
export type Order = { id: string; symbol: string; name: string; side: 'buy' | 'sell'; quantity: number; limit_price: string; status: 'pending' | 'filled' | 'cancelled' | 'expired'; reason: string; created_day: number; filled_day: number | null; fill_price: string | null; fees: string; created_at: string }
export type Account = { id: string; mode: string; day: number; cash: string; frozen_cash: string; available_cash: string; position_value: string; total_assets: string; rule_version: string; data_label: string; data_version: string; positions: { symbol: string; name: string; quantity: number; sellable: number; frozen: number; cost: string; price: string }[]; orders: Order[]; bars: Bar[]; quotes: Quote[]; ledger: { id: number; kind: string; cash_delta: string; quantity_delta: number; symbol: string | null; day: number; source: string }[] }
export type Course = { narration?: Narration | null; id: string; title: string; short_title: string; xp: number; badge: string; goal: string; minutes: number; prerequisites: string[]; practice: string; version: number; locked: boolean; completed: boolean; review_due: boolean; attempts: number; last_score: number; body?: string; questions?: { prompt: string; options: string[] }[] }
export type Feedback = { passed: boolean; explanation: string }
export type AnswerResult = { passed: boolean; score: number; feedback: Feedback[]; requirements: string[]; xp_awarded: number; message: string; lesson_id: string }
export type AuthUser = { locale: 'zh-CN' | 'en'; id: string; username: string; name: string; guide_step: number; guide_status: 'pending' | 'completed' | 'skipped' }
export type ReviewSummary = { due: number; scheduled: number; mastered: number; next_due_at: string | null }
export type ReviewItem = { id: string; lesson_id: string; title: string; stage: number; mistakes: number; review_count: number; due: boolean; due_at: string | null; revision: number; variant: number; content_version: number; question: { prompt: string; options: string[] } }
export type ReviewQueue = { summary: ReviewSummary; items: ReviewItem[] }
export type ReviewResult = { passed: boolean; explanation: string; stage: number; due_at: string | null; xp_awarded: number; message: string }
export type State = { player: AuthUser & { onboarded: boolean; xp: number; level: number; reduced_motion: boolean }; courses: Course[]; account: Account; reviews: ReviewSummary; rewards: { badge: string; xp: number; lesson_id: string; created_at: string }[]; last_attempt: { score: number; lesson_id: string; feedback: Feedback[]; created_at: string } | null; reflections: { id: string; plan: string; review: string; account_id: string; created_at: string }[] }
export type Job = { id: string; status: 'queued' | 'running' | 'completed' | 'failed'; params: { short_window: number; long_window: number; allocation: number; data_version: string; rule_version: string; strategy_version: string }; result: { total_return: string; max_drawdown: string; fees: string; trade_count: number; curve: { day: number; equity: string; benchmark: string; drawdown: string }[]; trades: { day: number; side: string; quantity: number; price: string; fees: string }[]; data_version: string; strategy_version: string; rule_version: string; matching: string; notes: string[] } | null; error: string | null; created_at: string }
export type Status = { database: string; teaching: { status: string; version: string; days: number }; worker: boolean; historical: string; forward: string; ai: string; vnpy: string; rules: { version: string; commission_note: string; sources: { title: string; url: string }[] } }
